import { DataApi } from './feature/cartSlide';
import { Datauser } from './feature/userSlide';

export const dataApi: DataApi[] = [
  {
    id: 1,
    title: 'Số 7 huyền thoại 2008',
    Url: 'https://vtv1.mediacdn.vn/thumb_w/640/2021/9/3/photo-1-1630617175459986897121.jpg',
    price: 45000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 276,
    qty: 1,
    Numberofwarehouses: 7,
    Sport: 1,
    Category: 'Áo quần thể thao',
    checkbox: false,
  },
  {
    id: 2,
    title: 'Vest sang trọng',
    Url: 'https://monamie.vn/image/5e7b3b695fa0261ef46bba5e/original.jpg',
    price: 75000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 146,
    qty: 1,
    Numberofwarehouses: 27,
    Sport: 0,
    Category: 'Áo quần Nam',
    checkbox: false,
  },
  {
    id: 3,
    title: 'Sơ mi cá tính',
    Url: 'https://www.elleman.vn/wp-content/uploads/2021/07/01/198104/top-cau-thu-mac-dep-euro-2020-_-CR7_-elle-man-2.jpeg',
    price: 39000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 1695,
    qty: 1,
    Numberofwarehouses: 201,
    Sport: 0,
    Category: 'Áo quần Nam',
    checkbox: false,
  },
  {
    id: 4,
    title: 'Đơn giản sành điệu',
    Url: 'https://vcdn1-giaitri.vnecdn.net/2021/08/03/IMG-6701-1627989769.jpg?w=1200&h=0&q=100&dpr=1&fit=crop&s=oZuWkEqvzdN8V8rODgPQdg',
    price: 54000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 423,
    qty: 1,
    Numberofwarehouses: 42,
    Sport: 0,
    Category: 'Áo quần Nam',
    checkbox: false,
  },
  {
    id: 5,
    title: 'Thể thao năng động',
    Url: 'https://i-giaitri.vnecdn.net/2018/06/13/CR7-13-1528856677_r_680x0.jpg',
    price: 75000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 56,
    qty: 1,
    Numberofwarehouses: 12,
    Sport: 0,
    Category: 'Áo quần thể thao',
    checkbox: false,
  },
  {
    id: 6,
    title: 'Đồ Biển',
    Url: 'https://vcdn1-giaitri.vnecdn.net/2021/08/03/IMG-6717-1627989780.jpg?w=1200&h=0&q=100&dpr=1&fit=crop&s=rJYbI-krwYZqcYQs37xKlA',
    price: 65000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 432,
    qty: 1,
    Numberofwarehouses: 55,
    Sport: 0,
    Category: 'Áo quần Nam',
    checkbox: false,
  },
  {
    id: 7,
    title: 'Đồ ngủ',
    Url: 'https://kenh14cdn.com/thumb_w/660/2020/9/16/photo-1-1600232541335263315479.jpg',
    price: 34000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 234,
    qty: 1,
    Numberofwarehouses: 65,
    Sport: 0,
    Category: 'Áo quần Nam',
    checkbox: false,
  },
  {
    id: 8,
    title: 'Số 7 huyền thoại 2022',
    Url: 'https://media.vov.vn/sites/default/files/styles/large/public/2022-11/cristiano_ronaldo_0.jpg',
    price: 47000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 5435,
    Numberofwarehouses: 4,
    Sport: 1,
    qty: 1,
    Category: 'Áo quần thể thao',
    checkbox: false,
  },
  {
    id: 9,
    title: 'Số 7 huyền thoại Real Madrid',
    Url: 'https://images2.minutemediacdn.com/image/fetch/w_2000,h_2000,c_fit/https%3A%2F%2Ftherealchamps.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2018%2F08%2F505383980.jpeg',
    price: 89000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 9895,
    Numberofwarehouses: 3,
    Sport: 1,
    qty: 1,
    Category: 'Áo quần thể thao',
    checkbox: false,
  },
  {
    id: 10,
    title: 'Số 7 huyền thoại Juventus',
    Url: 'https://icdn.juvefc.com/wp-content/uploads/2020/12/Cristiano-Ronaldo-940x494.jpg',
    price: 67000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 5435,
    Numberofwarehouses: 4,
    Sport: 1,
    qty: 1,
    Category: 'Áo quần thể thao',
    checkbox: false,
  },
  {
    id: 11,
    title: 'Số 7 huyền thoại Bồ Đào Nha',
    Url: 'https://image.thanhnien.vn/w1024/Uploaded/2022/oqivotiw/2021_10_13/cristiano-ronaldo-8329.jpeg',
    price: 76000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 5623,
    Numberofwarehouses: 9,
    Sport: 1,
    qty: 1,
    Category: 'Áo quần thể thao',
    checkbox: false,
  },
  {
    id: 12,
    title: 'Số 28 huyền thoại Sporting Lisbon',
    Url: 'https://vcdn1-thethao.vnecdn.net/2012/04/08/106e64e110220639ff082faef0d8ea15.jpg?w=480&h=0&q=100&dpr=1&fit=crop&s=uBi-ysCSVWrFSqwJ2BZfAg',
    price: 89000,
    description:
      'Hàng chất lượng cao, nhập khẩu chính hãng, đọc lạ duy nhất tại Việt nam',
    Qty: 543,
    qty: 1,
    Numberofwarehouses: 2,
    Sport: 1,
    Category: 'Áo quần thể thao',
    checkbox: false,
  },
];

export const Categorys = [
  { Category: 'Tất cả sản Phẩm' },
  { Category: 'Áo quần trẻ em' },
  { Category: 'Áo quần thể thao' },
  { Category: 'Áo quần nữ' },
  { Category: 'Áo quần Nam' },
  { Category: 'Giày dép' },
  { Category: 'Mũ nón' },
];

export const DataUser: Datauser[] = [
  {
    email: 'phuockha2852001@gmail.com',
    name: 'Kha',
    password: 'lephuockha',
    admin: 1,
  },
  {
    email: 'phuockha@gmail.com',
    name: 'Kha',
    password: 'lephuockha',
    admin: 0,
  },
  {
    email: 'phuockha285@gmail.com',
    name: 'Kha',
    password: 'lephuockha',
    admin: 0,
  },
];
